### ISSUE TITLE
Strange tabs layout using `guiset`

### ISSUE THREAD

**Issue by thmsaurel** [tridactyl/tridactyl#1989]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 70.0.1
Operating system: win

*   Brief description of the problem:

I've a strange tabs layout using guiset. I didn't make any configuration change inside userChrome others than the ones realize by `guiset`.

![image](https://user-images.githubusercontent.com/5463836/68657439-a1880500-052b-11ea-8a9c-4019b9b57dad.png)

I'm using tridactyl on Linux (archlinux) and Windows (10) with the latest Firefox available. On both computers, I've this issue.

*   Steps to reproduce:

1. clean you userChrome.css 
2. `guiset gui none`
3. `guiset tabs always`
4. restart Firefox

Sometimes, everything is right. But if you change the Firefox's theme, the error appears.

*   userChrome.css

```css
namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

statuspanel[type="overLink"],
#statuspanel[type="overLink"] {
  display: none !important;
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar {
  max-height: 0;
  min-height: 0!important;
  --tridactyl-auto-show-zone: 10px;
  margin-bottom: calc(-1 * var(--tridactyl-auto-show-zone));
  opacity: 0;
}

#navigator-toolbox::after {
  display: none !important;
}

#navigator-toolbox:not(:hover):not(:focus-within) #toolbar-menubar > * {
  background-color: rgb(232, 232, 231);
}

#main-window[sizemode="maximized"] #content-deck {
  padding-top: 8px;
}
```
