### ISSUE TITLE
Halloween theme breaks yanking

### ISSUE THREAD

**Issue by noctuid** [tridactyl/tridactyl#2025]
Tridactyl version: 1.17.0pre3297-8a4075e
Firefox version: Mozilla Firefox 70.0.1
Operating system: linux

# Reporting a bug / getting help

The halloween theme seems to break some commands, for example `hint -y`. I was trying to create a similar theme that put the commandline in the middle of the window and noticed this. This specifically seems to break things:
```css
/* don't show line when command line hidden */
.TridactylThemeHalloween #cmdline_iframe.hidden {
    display: none !important;
}
```
