### ISSUE TITLE
add a hints-only style

### ISSUE THREAD

**Issue by nilsbecker** [tridactyl/tridactyl#2996]
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 82.0.3
Operating system: mac

*   Brief description of the problem:

tridactyl applies heavy visual highlighting of clickable elements following vimperator but unlike vim-vixen and vimium-ff . there should be a style provided in the distribution that allows disabling this easily.

*   Steps to reproduce:

hit `f` 

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

i tried fixing this in `userContent.css` but this did not work satisfactorily, as it was not possible to fully disable element highlighting; also, after enabling `tridactylrc`, apparently userContent.css is not sourced anymore at all.

tridactylrc
```vim
" vim: filetype=vim

" delete all settings except what is here
sanitize tridactyllocal tridactylsync

" manage screen space
guiset_quiet hoverlink right

" key bindings for usability
bind d scrollpage +0.5
bind u scrollpage -0.5
bind x tabclose
bind X undo
unbind D
bind <C-j> tabmove -1
bind <C-k> tabmove +1
bind J tabprev
bind K tabnext
bind <C-i> mode ignore
bind / fillcmdline find
bind ? fillcmdline find -?
bind n findnext +1
bind N findnext -1
bind ,<Space> nohlsearch
set smoothscroll true

" from example rc files
bind gd tabdetach
bind gD composite tabduplicate; tabdetach
set newtab about:blank

" search and translate
set searchurls.translate https://translate.google.com/#view=home&op=translate&sl=%s1&tl=%s2&text=%s3
set searchurls.gs https:scholar.google.com/scholar?q=
```
usercontent.css
```css
span.TridactylHint {
	position: absolute !important;
	font-family: monospace !important;
	font-size: 14px !important;
	font-weight: bold !important;
	text-transform: lowercase !important;
	color: black !important;
	background-color: #ffd76e !important;
	border-color: rgba(0, 0, 0, 0.1) !important;
	border-width: 1px !important;
	border-radius: 2px !important;
	min-width: .75em !important;
	border-style: solid !important;
	padding: 0 1pt !important;
	text-align: center !important;
	z-index: 2147483647 !important;
}

.TridactylHintElem { 
	background-color: inherit !important;  
	border-color: rgba(0.5, 0.5, 0.5, 0.05) !important; 
} 

.TridactylHintActive { 
	background-color: rgba(1, 1, 0, 0.1) !important;
	color: black !important; 
	border-color: rgba(0, 0, 0, 0.1) !important; 
}

/** { font-family: serif ! important; }*/

```

generally speaking, i think relying on `userContent.css` is problematic as it's not synchronized between different devices, needs to be enabled explicitly by a config option with `legacy` in its name, and generally seems on the way out. a custom theme would be a  lot simpler to handle for users.

as a bonus, there could be one theme without any element highlighting as described above and another with just the element frames highlighted, which would be an intermediate solution
