### ISSUE TITLE
copying text with `;p` adds some CSS code into the text and 'hint' text at the end

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [tridactyl/tridactyl#4529]
### Reproducing the bug
1. go to: https://archlinux.org/mirrorlist/?country=all&protocol=https&ip_version=4&use_mirror_status=on

2. press the keybinding: `;p` to copy the text
- and you will get three letters
3. choose the outer hint's letter(first one) or second one

##
- If I choose the first letter I get this extra copied text to my actual text:

```css
@media print {
        .TridactylStatusIndicator {
            display: none !important;
        }
    }
```
and `hint`

- this is how it looks:

```css
@media print {
        .TridactylStatusIndicator {
            display: none !important;
        }
    }/*ACTUAL
TEXT
with
+1000
lines */
hint
```

- this is how it looks with cropped lines from the actual text:
```
@media print {
        .TridactylStatusIndicator {
            display: none !important;
        }
    }##
## Arch Linux repository mirrorlist
## Filtered by mirror score from mirror status page
## Generated on 2023-01-07
##

## France
#Server = https://mirrors.gandi.net/archlinux/$repo/os/$arch
## India
#Server = https://mirror.albony.xyz/archlinux/$repo/os/$arch
hint
```

- this is how it was suppose to look like (copied text):
```
##
## Arch Linux repository mirrorlist
## Filtered by mirror score from mirror status page
## Generated on 2023-01-07
##

## France
#Server = https://mirrors.gandi.net/archlinux/$repo/os/$arch
## India
#Server = https://mirror.albony.xyz/archlinux/$repo/os/$arch
```
If I choose the second letter I only get `hint` text to the end **and no problem on the last hint letter**

-   Tridactyl version (`:version`): `1.23.0pre6526-c663b8e2`

-   Firefox version (Top right menu > Help > About Firefox): `108.0.1 (64-bit)`
