### ISSUE TITLE
repl.it tells command line to be dark

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4659]
Tridactyl version: 1.23.0pre6724-2b6a27c6
Firefox version: Mozilla Firefox 106.0
Operating system: linux

1. visit https://replit.com/languages/nim
2. open command line
3. it is dark

Somehow the page is triggering `prefers-color-scheme: dark` which I didn't realise was possible.

I'm not 100% sure this is a bug? it looks kind of nice, to be honest

**Comment by bovine3dom** [comment]
Do you have an opinion about whether it is desired behaviour?

**Comment by Rhys-T** [comment]
Not particularly. It does mean that a site could theoretically force it to _not_ use dark mode, though…

Setting `color-scheme: normal;` on the `iframe` seems to override any CSS `color-scheme` inherited from the page, but it can still be affected by `<meta name="color-scheme">` - the only way to prevent that would be to directly set `color-scheme` to `light` or `dark` as appropriate. 

If anyone wants to try this out now, using `userContent.css`:
```css
/* You'll need to plug in the random "Internal UUID" for Tridactyl, found on about:debugging#/runtime/this-firefox */
iframe[src^="moz-extension://random00-uuid-for0-0000-tridactyl000/"] {
	color-scheme: light !important;
}
@media (prefers-color-scheme: dark) {
	iframe[src^="moz-extension://random00-uuid-for0-0000-tridactyl000/"] {
		color-scheme: dark !important;
	}
}

/* If Tridactyl gets changed to do this, and you want to go back to making it match the site: */
iframe[src^="moz-extension://random00-uuid-for0-0000-tridactyl000/"] {
	color-scheme: inherit !important;
}
```
