### ISSUE TITLE
this is how i changed my hint mode color box. (for light and dark mode)

### ISSUE THREAD

**Issue by Huansock** [tridactyl/tridactyl#4752]
# before the setting

you should know about userContent.css file on fire fox.

this is how you make your own userContent.css file on your firefox.

1. write a "about:profiles" on url and go to this site.
2. click "show in Finder" just next to Root directory.
3. open your directory (for example my directory is 61t7xboe.default-release)
4. find "chrome" folder. and open it.
5. if there already userContent.css exist, you can use it. Otherwise please create a new userContent.css file.
6. now go to "about:config" website and find "toolkit.legacyUserProfileCustomizations.stylesheets" and set it as "True".
7. write a css code. here is my userContent.css file for hint mode without color boxes.

```css
/* 
   dark background in new tabs without a white flash (with tridactyl newtab)
   @see: https://github.com/tridactyl/tridactyl/issues/2510
*/
:root { 
  /* these are variables for tridactyl css */
  --tridactyl-bg: #1d1b19 !important;
  --tridactyl-fg: white !important;
  /* if you wanna use outline then change following code lines */
  --tridactyl-hint-active-outline: none !important;
  --tridactyl-hint-outline: none !important;
  /* these are 2 setting for light mode , dark mode detect */
  color-scheme:light dark !important;
  supported-color-schemes: light dark !important;
  /* these are background-color for hint box and font-size */
  --tridactyl-hint-bg : none !important;
  --tridactyl-small-font-size: 17px !important;

}

/*
    set the background color of the new tab page (without tridactyl or with tridactyl without newtab)
*/
@-moz-document url-prefix(about:home), url-prefix(about:newtab) {
  body {
    background: #1d1b19;
  }
}

/* 
    if you set it straight to body element, it will be applied to the random web pages 
    that don't explicitly set the background color of their body element
    (there's many of those online)
*/
/* body { */
/* background-color: #1d1b19; */
/* } */             
/* light mode setting */
@media(prefers-color-scheme:light){
span.tridactylhint {
	position: absolute !important;
	font-family: "gill sans" !important;
	font-size: 17px !important;
	font-weight: normal !important;
	text-transform: lowercase !important;
	color: black !important;
  width: 2rem;
	background-color: rgba(230,240,230,0.9) !important;
	border-color: rgba(0,0,0,0) !important;
	border-width: 0px !important;
	border-radius: 0px !important;
	min-width: .75em !important;
	border-style: solid !important;
	padding: 0 0pt !important;
	text-align: center !important;
	z-index: 2147483647 !important;
  }
}

/* dark mode setting */
@media(prefers-color-scheme:dark){
span.tridactylhint {
	position: absolute !important;
	font-family: "gill sans" !important;
	font-size: 17px !important;
	font-weight: normal !important;
	text-transform: lowercase !important;
	color: black !important;
  width: 2rem;
	background-color: rgba(255,255,255,0.9) !important;
	border-color: rgba(0, 0, 0, 0) !important;
	border-width: 0px !important;
	border-radius: 2px !important;
	min-width: .75em !important;
	border-style: solid !important;
	padding: 0 0pt !important;
	text-align: center !important;
	z-index: 2147483647 !important;
}
}

.tridactylhintelem { background-color: none !important;  color: none !important; outline:none !important; } 
.tridactylhintactive { background-color: none !important; color: none !important; }

:root.tridactylthemenohl {
    --tridactyl-hint-active-bg: none !important;
    --tridactyl-hint-active-outline: none !important;
    --tridactyl-hint-outline: none !important;
    --tridactyl-hint-bg: none !important;
}
```
